#Define a generator function prime_number_generator that yields prime numbers indefinitely.Print the first 15 prime numbers generated by this function.

def prime_number_generator():
    num = 2
    while True:
        # Check if num is prime
        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                break
        else:
            yield num  
        num += 1
generator = prime_number_generator()
for _ in range(15):
    print(next(generator), end=" ")
